name: Build Release APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Automatically downloads the correct wrapper machinery straight into your main directory
      - name: Validate and Download Gradle Wrapper
        run: gradle wrapper

      - name: Build Release APK
        run: |
          chmod +x gradlew
          sed -i 's/\r$//' gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PPF-Release-APK
          path: app/build/outputs/apk/release/*.apk
